In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [7]:
df=pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
9049,10,101,76,48,180,32.9,0.171,63,0
9050,2,122,70,27,0,36.8,0.340,27,0
9051,5,121,72,23,112,26.2,0.245,30,0
9052,1,126,60,0,0,30.1,0.349,47,1
9053,1,93,70,31,0,30.4,0.315,23,0

In [9]:
col=df.columns
col

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [11]:
col_to_fix=[]
for c in col:
    if 0 in df[col].values:
        col_to_fix.append(c)
col_to_fix

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Outcome']

In [13]:
col_to_fix.remove('Outcome')

In [15]:
col_to_fix

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [17]:
for col in col_to_fix:
    df[col].replace(0,df[col].median())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
9049,10,101,76,48,180,32.9,0.171,63,0
9050,2,122,70,27,0,36.8,0.340,27,0
9051,5,121,72,23,112,26.2,0.245,30,0
9052,1,126,60,0,0,30.1,0.349,47,1
9053,1,93,70,31,0,30.4,0.315,23,0

In [19]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [21]:
df.shape

(9054, 9)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9054 entries, 0 to 9053
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               9054 non-null   int64
 1   Glucose                   9054 non-null   int64
 2   BloodPressure             9054 non-null   int64
 3   SkinThickness             9054 non-null   int64
 4   Insulin                   9054 non-null   int64
 5   BMI                       9054 non-null   float64
 6   DiabetesPedigreeFunction  9054 non-null   float64
 7   Age                       9054 non-null   int64
 8   Outcome                   9054 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 636.7 KB

In [27]:
x=df.drop('Outcome',axis=1)
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,138,62,35,0,33.6,0.127,47
1,0,84,82,31,125,38.2,0.233,23
2,0,145,0,0,0,44.2,0.630,31
3,0,135,68,42,250,42.3,0.365,24
4,1,139,62,41,480,40.7,0.536,21
...,...,...,...,...,...,...,...,...
9049,10,101,76,48,180,32.9,0.171,63
9050,2,122,70,27,0,36.8,0.340,27
9051,5,121,72,23,112,26.2,0.245,30
9052,1,126,60,0,0,30.1,0.349,47
9053,1,93,70,31,0,30.4,0.315,23

In [29]:
y=df['Outcome']
y

0       1
1       0
2       1
3       1
4       0
       ..
9049    0
9050    0
9051    0
9052    1
9053    0
Name: Outcome, Length: 9054, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y)

In [35]:
scaler=StandardScaler()
x_scaled_train=scaler.fit_transform(x_train)
x_scaled_test=scaler.transform(x_test)

In [37]:
models=[]
models.append(('Linear',LinearRegression()))
models.append(('Nav',GaussianNB()))
models.append(('dec',DecisionTreeClassifier()))

In [39]:
for name,model in models:
    model.fit(x_scaled_train,y_train)

In [41]:
names=[]
scores=[]

for name,model in models:
    y_unknown_values=model.predict(x_scaled_test)
    names.append(name)
    scores.append(y_unknown_values)

In [43]:
df_results = pd.DataFrame({
    'Model': names,
    'Accuracy': scores
})
df_results

    Model                                           Accuracy
0  Linear  [0.0159803674260226, 0.23229036468613362, 0.57...
1     Nav  [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, ...
2     dec  [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, ...

In [45]:
import pandas as pd

df_preds = pd.DataFrame()

for name, model in models:
    y_pred = model.predict(x_scaled_test)
    df_preds[name] = y_pred   # ✅ each model becomes a column

print(df_preds.head())

     Linear  Nav  dec
0  0.015980    0    0
1  0.232290    0    0
2  0.573297    0    0
3  0.335638    0    0
4  0.564813    1    0

In [47]:
tuv=LinearRegression()
tuv.fit(x_scaled_train,y_train)
y_prediction=tuv.predict(x_scaled_test)

In [49]:
data_comp=pd.DataFrame({'actual':y_test.values,'predict':y_prediction})
data_comp

      actual   predict
0          0  0.015980
1          0  0.232290
2          0  0.573297
3          0  0.335638
4          0  0.564813
...      ...       ...
1806       0  0.124264
1807       1  0.519250
1808       0 -0.099314
1809       0  0.221041
1810       1  0.229031

[1811 rows x 2 columns]

In [51]:
data_comp['predict']=data_comp['predict'].map(lambda x:1 if x>=0.5 else 0).astype(int)

In [53]:
data_comp

      actual  predict
0          0        0
1          0        0
2          0        1
3          0        0
4          0        1
...      ...      ...
1806       0        0
1807       1        1
1808       0        0
1809       0        0
1810       1        0

[1811 rows x 2 columns]

In [55]:
correct=data_comp[data_comp['actual']==data_comp['predict']]

In [57]:
wrong=data_comp[data_comp['actual']!=data_comp['predict']]

In [61]:
correct

      actual  predict
0          0        0
1          0        0
3          0        0
5          1        1
6          0        0
...      ...      ...
1805       0        0
1806       0        0
1807       1        1
1808       0        0
1809       0        0

[1396 rows x 2 columns]

In [63]:
wrong

      actual  predict
2          0        1
4          0        1
7          1        0
9          1        0
10         1        0
...      ...      ...
1785       0        1
1792       1        0
1793       0        1
1800       1        0
1810       1        0

[415 rows x 2 columns]

In [65]:
accuracy = (data_comp['actual'] == data_comp['predict']).mean()

In [67]:
accuracy

0.7708448371065709

In [69]:
from sklearn.metrics import accuracy_score

accuracy_score(data_comp['actual'], data_comp['predict'])

0.7708448371065709

In [75]:
df_results.query('Model=="Nav"')

  Model                                           Accuracy
1   Nav  [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, ...

In [79]:
nav_pred = df_results.query('Model=="Nav"')['Accuracy'].iloc[0]

df_nav = pd.DataFrame({
    'Actual': y_test.values,
    'predict': nav_pred
})

df_nav

      Actual  predict
0          0        0
1          0        0
2          0        0
3          0        0
4          0        1
...      ...      ...
1806       0        0
1807       1        0
1808       0        0
1809       0        0
1810       1        0

[1811 rows x 2 columns]

In [87]:
corect=df_nav[df_nav['Actual']==df_nav['predict']]

In [89]:
wrong=df_nav[df_nav['Actual']==df_nav['predict']]

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(df_nav['Actual'], data_comp['predict'])